/*         Character Makefile        */
/* Generated by Rane's V2 CHR editor */

pcx_name=DEFAULT;
chr_name=DEFAULT;
frame_w=16;
frame_h=20;
hot_x=0;
hot_y=8;
hot_w=8;
hot_h=8;
per_row=18;
total_frames=60;
lidle=0;
ridle=3;
uidle=9;
didle=6;
lscript=F0W12F1W12F0W12F2W12;
rscript=F3W12F4W12F3W12F5W12;
uscript=F9W12F10W12F9W12F11W12;
dscript=F6W12F7W12F6W12F8W12;

/* End of generated file. */
